[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

authors = ["Phi <code@phictional.de>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.3"
rand = "0.8"
